# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaron', '0002_player_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_started',
            field=models.BooleanField(default=0),
        ),
    ]
