# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaron', '0003_game_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules_t',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rules_v',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rules_wl',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='visible',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
