# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaron', '0004_auto_20170219_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(),
        ),
    ]
